arucikk_typ_gen.sql
alaplap_typ_gen.sql
cpu_typ_gen.sql
hdd_typ_gen.sql
video_typ_gen.sql
memoria_typ_gen.sql
felhasznalo_tab_gen.sql
raktar_tab_gen.sql
szamla_tab_gen.sql
tetel_tab_gen.sql
hozzaszolas_tab_gen.sql;
